[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
board_build.embed_txtfiles =
    web/chart.umd.min.js
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -UCONFIG_ARDUHAL_ESP_LOG
    -DCONFIG_CAMERA_JPEG_MODE_FRAME_SIZE_AUTO=1
    -Ilib/esp32-camera-gc0328/driver/include
    -Ilib/esp32-camera-gc0328/driver/private_include
    -Ilib/esp32-camera-gc0328/conversions/include
    -Ilib/esp32-camera-gc0328/conversions/private_include
    -Ilib/esp32-camera-gc0328/sensors/private_include
    -Ilib/esp32-camera-gc0328/target/private_include
